mysql:
  enabled: false
  port: 3306
  username: root
  hostname: localhost
  password: ''
  database: minecraft
  prefix: "Ls_"
preferAsyncDBCalls: true
setUnregisteredLifestonesToAir: true
protectLifestoneRadius: 3
debugMessages: false
attuneDelay: 5
recallDelay: 10
protectPlayerAfterRecallDuration: 10
randomTPRadius: 1000
rowsPerPage: 10