name: Lifestones
main: com.cyprias.Lifestones.Lifestones
version: 1.8.0

commands:
  lifestones:
    description: Lifestones commands.
    usage: /<command>
  lifestone:
    description: Recall to lifestone
    usage: /<command>

permissions:
  lifestones.*:
    description: Gives access to all lifestones commands
    default: false
    children:
      lifestones.user: true
      lifestones.admin: true
  lifestones.user:
    description: Gives access to general user commands.
    default: false
    children:
      lifestones.recall: true
      lifestones.attune: true
      lifestones.release: true
  lifestones.admin:
    description: Gives access to admin commands.
    default: false
    children:
      lifestones.create: true
      lifestones.breaklifestone: true
      lifestones.modifyprotectedblocks: true
      lifestones.reload: true
      lifestones.randomtp: true
      lifestones.tp: true
      lifestones.list: true
      lifestones.near: true
      lifestones.attunement: true
  lifestones.attunement:
    description: Attunement commands.
    default: false
    children:
      lifestones.attunement.setdefault: true
      lifestones.attunement.list: true
      lifestones.attunement.tp: true